import { useEffect, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Clock3, Lock, Save } from 'lucide-react';
import './practice.css';

type Question = { prompt: string; options: string[]; answer: number; explanation: string; topic: string };
const questions: Question[] = [
  { prompt: 'Which HTTP method is normally used to retrieve a resource?', options: ['POST', 'GET', 'PATCH', 'DELETE'], answer: 1, explanation: 'GET retrieves a representation without changing the resource.', topic: 'HTTP basics' },
  { prompt: 'Which status code means a request was successful?', options: ['201', '301', '404', '200'], answer: 3, explanation: '200 OK indicates that the request completed successfully.', topic: 'HTTP basics' },
  { prompt: 'What does a primary key provide in a relational table?', options: ['A unique row identity', 'A sorted file', 'A backup copy', 'A user permission'], answer: 0, explanation: 'A primary key uniquely identifies each row in a table.', topic: 'SQL basics' },
  { prompt: 'Which normal form removes repeating groups?', options: ['First normal form', 'Second normal form', 'Third normal form', 'Boyce-Codd normal form'], answer: 0, explanation: 'First normal form requires atomic values and removes repeating groups.', topic: 'Database design' },
  { prompt: 'Which browser API stores small key-value data locally?', options: ['localStorage', 'WebSocket', 'Fetch', 'Canvas'], answer: 0, explanation: 'localStorage stores string key-value pairs in the browser.', topic: 'Browser APIs' }
];

export function PracticeHome() {
  const [activeSet, setActiveSet] = useState<string | null>(null);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [current, setCurrent] = useState(0);
  const [seconds, setSeconds] = useState(45 * 60);
  const [submitted, setSubmitted] = useState(false);
  const [savedAt, setSavedAt] = useState('Not started');
  const sets = [{ id: 'mid-cse', subject: 'Web Technologies', code: 'CSE301', title: 'Mid-Term Practice', attempts: 2, score: '76%', premium: false }, { id: 'end-cse', subject: 'Web Technologies', code: 'CSE301', title: 'End-Term Practice', attempts: 0, score: '—', premium: true }, { id: 'mid-mca', subject: 'Database Management', code: 'MCA204', title: 'Mid-Term Practice', attempts: 2, score: '68%', premium: false }, { id: 'end-mca', subject: 'Database Management', code: 'MCA204', title: 'End-Term Practice', attempts: 0, score: '—', premium: true }];
  useEffect(() => { if (!activeSet || submitted) return; const timer = window.setInterval(() => setSeconds((value) => { if (value <= 1) { window.clearInterval(timer); setSubmitted(true); return 0; } return value - 1; }), 1000); return () => window.clearInterval(timer); }, [activeSet, submitted]);
  useEffect(() => { if (activeSet && !submitted) { setSavedAt('Saved just now'); const timer = window.setTimeout(() => setSavedAt('Saved just now'), 500); return () => window.clearTimeout(timer); } }, [answers, activeSet, submitted]);
  const start = (setId: string) => { setActiveSet(setId); setAnswers({}); setCurrent(0); setSeconds(45 * 60); setSubmitted(false); setSavedAt('Saved just now'); };
  const submit = () => setSubmitted(true);
  if (activeSet && submitted) { const score = questions.reduce((total, question, index) => total + (answers[index] === question.answer ? 1 : 0), 0); return <div className="page-stack"><div className="result-header"><div><p className="eyebrow">Attempt complete</p><h2>Mid-Term Practice results</h2><p className="muted">Your result is private to you unless you choose to share it.</p></div><strong className="result-score">{score}/{questions.length}</strong></div><section className="panel"><div className="panel-heading"><h2>Answers and explanations</h2><span className="badge success">Submitted</span></div>{questions.map((question, index) => <div className="result-row" key={question.prompt}><div><strong>{index + 1}. {question.prompt}</strong><small>Your answer: {answers[index] === undefined ? 'Not answered' : question.options[answers[index]]}</small><p>{question.explanation}</p></div><span className={`badge ${answers[index] === question.answer ? 'success' : 'warning'}`}>{answers[index] === question.answer ? 'Correct' : 'Review'}</span></div>)}</section><button className="secondary-button" onClick={() => setActiveSet(null)}>Back to practice</button></div>; }
  if (activeSet) { const question = questions[current]; const minutes = Math.floor(seconds / 60).toString().padStart(2, '0'); const remaining = (seconds % 60).toString().padStart(2, '0'); return <div className="page-stack"><div className="test-header"><div><p className="eyebrow">Sample content</p><h2>Mid-Term Practice · {sets.find((set) => set.id === activeSet)?.subject}</h2><span className="saved-status"><Save size={13} />{savedAt}</span></div><div className="timer"><Clock3 size={16} />{minutes}:{remaining}</div></div><div className="test-layout"><section className="panel question-panel"><div className="question-meta"><span>Question {current + 1} of {questions.length}</span><span>{question.topic}</span></div><h3>{question.prompt}</h3><div className="answer-options">{question.options.map((option, index) => <button className={answers[current] === index ? 'selected' : ''} key={option} onClick={() => setAnswers({ ...answers, [current]: index })}><span>{String.fromCharCode(65 + index)}</span>{option}{answers[current] === index && <Check size={16} />}</button>)}</div><div className="question-footer"><button className="secondary-button" disabled={current === 0} onClick={() => setCurrent(current - 1)}><ChevronLeft size={15} />Previous</button><button className="primary-button" onClick={() => current === questions.length - 1 ? submit() : setCurrent(current + 1)}>{current === questions.length - 1 ? 'Submit attempt' : 'Next question'}<ChevronRight size={15} /></button></div></section><aside className="panel question-nav"><h3>Questions</h3><div>{questions.map((_, index) => <button className={`${index === current ? 'current' : ''} ${answers[index] !== undefined ? 'answered' : ''}`} key={index} onClick={() => setCurrent(index)}>{index + 1}</button>)}</div><p>Auto-submit occurs when the timer reaches zero.</p></aside></div></div>; }
  return <div className="page-stack"><div className="practice-tabs"><button className="practice-tab active"><span>Practice sets</span><small>Two subjects · Sample content</small></button><button className="practice-tab"><span>Topic quiz</span><small>Choose a unit</small></button></div><div className="practice-set-grid">{sets.map((set) => <article className={`practice-set ${set.premium ? 'locked' : ''}`} key={set.id}><div className="set-top"><span className="badge neutral">{set.code}</span>{set.premium ? <Lock size={17} /> : <span className="badge success">Free sample</span>}</div><h3>{set.title}</h3><p>{set.subject} · 40 MCQs + 5 written questions</p><div className="set-stat"><span>{set.attempts} attempts</span><strong>{set.score}</strong></div>{set.premium ? <button className="secondary-button" onClick={() => undefined}><Lock size={14} />This set is part of Plus</button> : <button className="primary-button" onClick={() => start(set.id)}>Start practice <ChevronRight size={15} /></button>}</article>)}</div><div className="practice-note"><Check size={17} /><span>Each result includes the correct answer and a plain-language explanation. Topic suggestions always show their reason.</span></div></div>;
}
