import { useState } from 'react';
import { CalendarPlus, Camera, Check, Copy, Download, Mic, MicOff, MonitorUp, PhoneOff, Video, X } from 'lucide-react';
import './interviews.css';

type Role = 'student' | 'mentor' | 'interviewer' | 'counsellor' | 'admin' | 'data-steward';
type Interview = { id: string; student: string; interviewer: string; date: string; time: string; duration: string; topic: string; status: string };

const initialInterviews: Interview[] = [{ id: 'i-1', student: 'Aanya Sharma', interviewer: 'Prof. R. Mehta', date: '2026-10-17', time: '15:30', duration: '45', topic: 'Project discussion', status: 'Upcoming' }, { id: 'i-2', student: 'Rohan Gupta', interviewer: 'Arjun Nair', date: '2026-10-16', time: '09:30', duration: '30', topic: 'Technical screening', status: 'Completed' }];

export function InterviewsWorkspace({ role }: { role: Role }) {
  const [interviews, setInterviews] = useState(initialInterviews); const [scheduleOpen, setScheduleOpen] = useState(role === 'interviewer'); const [selected, setSelected] = useState<Interview | null>(null); const [toast, setToast] = useState('');
  const createInterview = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const interview: Interview = { id: crypto.randomUUID(), student: String(form.get('student')), interviewer: String(form.get('interviewer')), date: String(form.get('date')), time: String(form.get('time')), duration: String(form.get('duration')), topic: String(form.get('topic')), status: 'Upcoming' }; setInterviews((current) => [...current, interview]); setScheduleOpen(false); setToast('Interview scheduled. Calendar invite is ready.'); window.setTimeout(() => setToast(''), 3500); };
  const downloadCalendar = (interview: Interview) => { const ics = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'BEGIN:VEVENT', `SUMMARY:SuccessHUB interview with ${interview.student}`, `DTSTART:${interview.date.replace(/-/g, '')}T${interview.time.replace(':', '')}00`, `DURATION:PT${interview.duration}M`, `DESCRIPTION:${interview.topic}`, 'END:VEVENT', 'END:VCALENDAR'].join('\r\n'); const url = URL.createObjectURL(new Blob([ics], { type: 'text/calendar' })); const link = document.createElement('a'); link.href = url; link.download = 'successhub-interview.ics'; link.click(); URL.revokeObjectURL(url); };
  return <div className="page-stack">{toast && <div className="toast"><Check size={16} />{toast}</div>}<div className="content-grid interview-page-grid"><section className="panel"><div className="panel-heading"><h2>Upcoming interviews</h2><button className="primary-button" onClick={() => setScheduleOpen(true)}><CalendarPlus size={15} />Schedule interview</button></div><div className="interview-list">{interviews.map((interview) => <button className="interview-list-row" key={interview.id} onClick={() => setSelected(interview)}><span className="date-block"><strong>{new Date(`${interview.date}T${interview.time}`).toLocaleDateString('en-IN', { day: '2-digit' })}</strong><small>{new Date(`${interview.date}T${interview.time}`).toLocaleDateString('en-IN', { month: 'short' })}</small></span><span><strong>{interview.student}</strong><small>{interview.topic} · {interview.duration} min</small></span><span className={`badge ${interview.status === 'Completed' ? 'success' : 'neutral'}`}>{interview.status}</span></button>)}</div></section><section className="panel"><div className="panel-heading"><h2>Waiting room</h2><span className="badge neutral">Recording off</span></div>{selected ? <WaitingRoom interview={selected} onClose={() => setSelected(null)} onCalendar={() => downloadCalendar(selected)} /> : <div className="empty-state compact"><Video size={24} /><h2>Select an interview</h2><p>Open an upcoming interview to test the waiting room and call.</p></div>}</section></div><section className="panel"><div className="panel-heading"><h2>Feedback rubric</h2><span className="muted">Advisory only</span></div><div className="rubric-grid">{['Communication', 'Technical skill', 'Problem solving', 'Confidence'].map((label) => <label className="rubric-input" key={label}><span>{label}</span><select defaultValue=""><option value="" disabled>Score</option><option>1 - Needs support</option><option>2</option><option>3</option><option>4</option><option>5 - Strong</option></select><textarea placeholder="Written comment" rows={2} /></label>)}</div></section>{scheduleOpen && role !== 'student' && <ScheduleForm onSubmit={createInterview} onClose={() => setScheduleOpen(false)} />}</div>;
}

function ScheduleForm({ onSubmit, onClose }: { onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; onClose: () => void }) { return <div className="modal-backdrop"><form className="form-modal schedule-modal" onSubmit={onSubmit}><div className="preview-header"><strong>Schedule an interview</strong><button type="button" className="icon-button" aria-label="Close schedule form" onClick={onClose}><X size={18} /></button></div><label>Student<select name="student" required><option>Aanya Sharma</option><option>Rohan Gupta</option><option>Meera Iyer</option></select></label><label>Interviewer<select name="interviewer" required><option>Prof. R. Mehta</option><option>Arjun Nair</option></select></label><div className="form-row"><label>Date<input type="date" name="date" required defaultValue="2026-10-17" /></label><label>Time<input type="time" name="time" required defaultValue="15:30" /></label></div><div className="form-row"><label>Duration<select name="duration"><option>30</option><option>45</option><option>60</option></select></label><label>Topic<input name="topic" required defaultValue="Project discussion" /></label></div><button className="primary-button" type="submit">Schedule and create invite <CalendarPlus size={15} /></button></form></div>; }

function WaitingRoom({ interview, onClose, onCalendar }: { interview: Interview; onClose: () => void; onCalendar: () => void }) { const [joined, setJoined] = useState(false); const [camera, setCamera] = useState(true); const [mic, setMic] = useState(true); const [permissionMessage, setPermissionMessage] = useState(''); const join = async () => { try { await navigator.mediaDevices?.getUserMedia({ video: camera, audio: mic }); setJoined(true); } catch { setPermissionMessage('Camera or microphone access was denied. You can still join with both devices off.'); } }; if (joined) return <div className="call-room"><div className="call-main"><div className="call-tile self"><Video size={30} /><span>{interview.student}</span></div><div className="call-controls"><button className="icon-button" aria-label="Toggle microphone" onClick={() => setMic(!mic)}>{mic ? <Mic /> : <MicOff />}</button><button className="icon-button" aria-label="Toggle camera" onClick={() => setCamera(!camera)}><Camera /></button><button className="icon-button"><MonitorUp /></button><button className="hangup" aria-label="Leave call" onClick={onClose}><PhoneOff size={17} /></button></div></div><aside className="call-sidebar"><strong>In-call chat</strong><p className="muted">Waiting for the interviewer to admit you.</p><strong>Shared notes</strong><textarea placeholder="Notes are visible to the interviewer" /></aside></div>; return <div className="waiting-room"><div className="preview-tile"><Video size={27} /><strong>Camera and microphone preview</strong><span>{camera ? 'Camera on' : 'Camera off'} · {mic ? 'Microphone on' : 'Microphone off'}</span></div><div className="device-controls"><button className={`secondary-button ${!camera ? 'selected-control' : ''}`} onClick={() => setCamera(!camera)}><Camera size={15} />Camera</button><button className={`secondary-button ${!mic ? 'selected-control' : ''}`} onClick={() => setMic(!mic)}><Mic size={15} />Microphone</button></div><div className="waiting-copy"><h3>{interview.student === 'Aanya Sharma' ? 'You are early.' : 'Waiting room'}</h3><p>Interview with {interview.interviewer} · {interview.date} at {interview.time}</p><span className="recording-off"><span />Recording is off</span>{permissionMessage && <div className="error-banner">{permissionMessage}</div>}<div className="waiting-actions"><button className="primary-button" onClick={join}>Join call <Video size={15} /></button><button className="secondary-button" onClick={onCalendar}><Download size={15} />Download calendar invite</button><button className="icon-button" aria-label="Copy interview link"><Copy size={16} /></button></div></div></div>; }
