import { useState } from 'react';
import { Check, CreditCard, FileText, ShieldCheck, X } from 'lucide-react';
import './payments.css';

type View = 'pricing' | 'purchases';
type Plan = { id: string; name: string; monthly: number; yearly: number; description: string; features: string[] };
const plans: Plan[] = [{ id: 'free', name: 'Free', monthly: 0, yearly: 0, description: 'Core support and sample content.', features: ['Support conversations', 'One free practice set per subject', 'Sample note previews'] }, { id: 'plus', name: 'Plus', monthly: 149, yearly: 1199, description: 'More notes and practice sets.', features: ['Everything in Free', 'All note previews and allowed downloads', 'All practice sets'] }, { id: 'pro', name: 'Pro', monthly: 299, yearly: 2399, description: 'Plus with one mock interview each month.', features: ['Everything in Plus', 'One mock interview per month', 'Interview feedback history'] }];

export function PricingPage({ initialView }: { initialView: View }) { const [view, setView] = useState(initialView); const [billing, setBilling] = useState<'monthly' | 'yearly'>('monthly'); const [checkout, setCheckout] = useState<Plan | null>(null); const [accepted, setAccepted] = useState(false); const [state, setState] = useState<'idle' | 'success' | 'failure'>('idle'); const startCheckout = (plan: Plan) => { if (!plan.monthly) return; setCheckout(plan); setState('idle'); setAccepted(false); }; const pay = () => { if (!accepted) return; setState(Math.random() > 0.15 ? 'success' : 'failure'); };
  if (view === 'purchases') return <div className="page-stack"><div className="test-banner">Test mode - no real money is charged.</div><section className="panel purchase-panel"><div className="panel-heading"><h2>Current subscription</h2><span className="badge success">Active</span></div><div className="purchase-summary"><div><strong>Plus · Monthly</strong><span>Renews 9 Nov 2026 · Razorpay test order</span></div><button className="secondary-button">Cancel subscription</button></div></section><section className="panel"><div className="panel-heading"><h2>Purchases and receipts</h2></div><div className="purchase-row"><FileText size={18} /><div><strong>Plus subscription</strong><span>9 Oct 2026 · ₹149.00 · Paid</span></div><button className="text-button">Download receipt</button></div></section></div>;
  return <div className="page-stack"><div className="test-banner">Test mode - no real money is charged.</div><div className="billing-switch"><button className={billing === 'monthly' ? 'active' : ''} onClick={() => setBilling('monthly')}>Monthly</button><button className={billing === 'yearly' ? 'active' : ''} onClick={() => setBilling('yearly')}>Yearly <span>Save with annual billing</span></button></div><div className="plan-grid">{plans.map((plan) => <article className={`plan-card ${plan.id === 'plus' ? 'recommended' : ''}`} key={plan.id}>{plan.id === 'plus' && <span className="recommend-label">Most used</span>}<h2>{plan.name}</h2><p>{plan.description}</p><strong className="plan-price">₹{billing === 'monthly' ? plan.monthly : plan.yearly}<small>{plan.monthly ? `/${billing === 'monthly' ? 'month' : 'year'}` : ''}</small></strong><ul>{plan.features.map((feature) => <li key={feature}><Check size={15} />{feature}</li>)}</ul><button className={plan.id === 'free' ? 'secondary-button' : 'primary-button'} onClick={() => startCheckout(plan)}>{plan.id === 'free' ? 'Current plan' : `Choose ${plan.name}`}</button></article>)}</div><p className="legal-note"><ShieldCheck size={15} />Prices are editable by administrators. Terms, privacy, refund and GST notes are drafts pending university review.</p>{checkout && <div className="modal-backdrop" onMouseDown={() => setCheckout(null)}><div className="form-modal checkout-modal" onMouseDown={(event) => event.stopPropagation()}><div className="preview-header"><strong>Checkout · {checkout.name}</strong><button className="icon-button" onClick={() => setCheckout(null)} aria-label="Close checkout"><X size={18} /></button></div>{state === 'idle' && <><div className="checkout-amount"><span>Amount</span><strong>₹{billing === 'monthly' ? checkout.monthly : checkout.yearly}</strong></div><label className="checkbox-label"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} />I accept the draft Terms and Refund Policy for this test checkout.</label><p className="muted small-copy">Razorpay hosted Checkout will handle payment details. SuccessHUB stores only order ID, payment ID, amount and status.</p><button className="primary-button" onClick={pay} disabled={!accepted}><CreditCard size={15} />Open Razorpay test checkout</button></>}{state === 'success' && <CheckoutResult title="Payment successful" message="Your test entitlement is active. A receipt is available in Purchases." success onClose={() => setCheckout(null)} />}{state === 'failure' && <CheckoutResult title="Payment needs another try" message="The test payment was not completed. No access was granted." onClose={() => setState('idle')} />}</div></div>}</div>;
}

function CheckoutResult({ title, message, success, onClose }: { title: string; message: string; success?: boolean; onClose: () => void }) { return <div className="checkout-result"><span className={`result-icon ${success ? 'success' : ''}`}>{success ? <Check size={22} /> : <CreditCard size={22} />}</span><h2>{title}</h2><p>{message}</p><button className="primary-button" onClick={onClose}>{success ? 'Close' : 'Try again'}</button></div>; }
